import base64
import io
import json
import re
from pathlib import Path

import httpx
from PIL import Image

from app.config import settings

NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"

GENERIC_MST_PROMPT = """Analyze this Vietnamese business document.
Extract the following and return valid JSON only, no markdown:
{
  "tax_code": "MST of the SELLER or VENDOR (người bán) — string or null",
  "document_type": "purchase_order or vendor_bill or null",
  "order_number": "the document/order number (Số PO, Số chứng từ, P/O Number, Supplier Delivery ID, Số phiếu giao hàng, etc.) — string or null",
  "format_hint": "one of: osifood | seven_eleven | coopfood | standard — detect from document layout/brand"
}
format_hint rules:
- "osifood": document has columns numbered (1)(2)... at top, column names at BOTTOM, or says OsiFood/OSIFOOD
- "seven_eleven": document says PHIẾU GIAO HÀNG or DELIVERY NOTE or 7-ELEVEN or Supplier Delivery ID
- "coopfood": document was generated by JDA Software, has P/O Location, Ord/CS, Ord/Pcs columns, or says Co.opfood/Co.opmart
- "standard": anything else"""

GENERIC_FULL_PROMPT = """You are an expert at extracting structured data from Vietnamese business documents (purchase orders / đơn đặt hàng and VAT invoices / hóa đơn GTGT).

CRITICAL REQUIRED FIELDS (MUST extract):
- order_date: Ngày đặt hàng (YYYY-MM-DD format, REQUIRED)
- delivery_date: Ngày giao hàng / Ngày nhận hàng dự kiến (YYYY-MM-DD format, REQUIRED)
- total_amount: Tổng giá trị đơn hàng (number, REQUIRED)
- items[].quantity: Số lượng (number, REQUIRED for each item)
- items[].unit: Đơn vị tính (string, REQUIRED for each item)
- items[].line_total: Thành tiền (number, REQUIRED for each item)

DOUBLECHECK RULES:
- order_date MUST be DIFFERENT from delivery_date (delivery is always AFTER order date)
- total_amount should approximately equal SUM of all items[].line_total (with possible tax/discount)
- If you see multiple dates, order_date is the EARLIER one, delivery_date is the LATER one
- If a field labeled "Ngày Đặt Hàng" exists, that is order_date. "Ngày Giao Hàng" is delivery_date.
- DO NOT confuse them. Read the label carefully.
- If total_amount has both "before VAT" and "after VAT" versions, use the FINAL total (after VAT)

FIELD ALIASES — the same field may appear under many different labels:
- order_number: "Số PO", "SỐ PO", "PO No.", "PO No", "P/O Number", "Order No.", "Order No", "Số chứng từ", "Số đơn hàng", "SỐ ĐƠN ĐẶT HÀNG", "Đơn đặt hàng số", "Số thứ tự đơn đặt hàng", "Số hiệu đơn hàng", "OUR REF NO", "Ord slip no", "Supplier Delivery ID"
- order_date: "Ngày đặt hàng", "Ngày chứng từ", "Ngày đặt đơn", "NGÀY ĐẶT HÀNG", "Order Date", "Ord dt", "DATE", "Date", "Entry Date", "Ngày đặt hàng/Date", "PO Date"
- delivery_date: "Ngày giao hàng", "Ngày nhận hàng", "Delivery Date", "Ngày giao", "NGÀY GIAO HÀNG", "Expected Delivery", "Ngày dự kiến giao", "Ngày xác nhận", "Confirmation Date"
- delivery_address: "Ship to", "Ship To", "GIAO TỚI", "Địa chỉ giao hàng", "ĐỊA CHỈ GIAO HÀNG", "Nơi giao hàng", "Giao hàng tại kho", "ĐỊA ĐIỂM GIAO HÀNG", "SHIP ADDRESS", "Delivered To", "Delivery to", "Delivery Address", "Delivery to / Giao hàng tới"
- payment_method: "Phương thức thanh toán", "HÌNH THỨC THANH TOÁN", "Thanh toán", "Terms", "TERMS", "Payment Terms"
- recipient_name: "Người nhận hàng", "NNH", "Người liên hệ", "Attn", "Contact", "CONTACT"
- customer_name: The BUYER who placed the order (Đơn vị mua hàng, Ordered By, Bill To, Kính gửi, Store Name, Tên cửa hàng, CUSTOMER). This is the company that ORDERS goods. Look for store/branch name, "Giao tới", "Ship to" company name.
- vendor_name: The SELLER/SUPPLIER who fulfills the order (NHÀ CUNG CẤP, VENDOR, Supplier, Đơn vị bán hàng, By Supplier). On purchase orders sent TO Satori, vendor_name = "Satori" — DO NOT use this as customer_name.
- customer_tax_code: MST of the BUYER (not the vendor/supplier)
- items.product_code: "Item No.", "Item Code", "Mã hàng", "PLU CODE", "SKU Number", "Article", "Prod cd", "Mã sản phẩm", "Mã SP của NCC", "MÃ GỢI NHỚ", "CK Item Code"
- items.product_name: "Description", "Tên hàng", "TÊN HÀNG HÓA", "Tên mặt hàng", "Article Desc", "Article Description", "Prod nm", "Tên sản phẩm", "Unit Barcode Description"
- items.quantity: "Qty", "Quantity", "Số lượng", "Ord qty", "Order Qty", "SL Đặt", "SL ĐẶT HÀNG", "OU Qty", "Sply qty", "PO Qty."
- items.unit: "UoM", "UOM", "Đvt", "ĐVT", "Unit", "Spec", "Đơn vị"
- items.unit_price: "Price", "Unit Price", "Đơn giá", "GIÁ VỐN ĐVỊ (0VAT)", "Pur. Price (-VAT)", "Buy Cost", "Net Buy Cost", "UNIT COST", "Sply prc", "Đơn giá lẻ sau VAT", "Đơn giá (-VAT)", "Đơn giá cuối (-VAT)"
- items.tax_rate: "VAT", "VAT(%)", "VAT Rate", "Tax Rate", "THUẾ SUẤT", "Tax rt", "% VAT"
- items.discount_rate: "% CK", "CK%", "CK trực tiếp", "% KM Giảm Giá", "Discount"
- items.line_total: "Total", "Amount", "Thành tiền", "THÀNH TiỀN", "Extended Cost", "Sply amt", "Sub Total", "Amount (-VAT)", "Thành tiền (-VAT)"
- total_amount: "Total Amount", "TỔNG CỘNG", "Tổng cộng", "Grand Total", "TOTAL BF.TAX", "Thành tiền (No VAT)", "Tổng giá trị trước thuế", "Sub Total", "Total Net Purchase Price"
- tax_amount: "VAT amount", "Thuế GTGT", "TOTAL VAT", "Total VAT", "Tax", "VAT AMT", "Tot add tax"

Extract all information and return valid JSON only (no markdown, no explanation):
{
  "document_type": "purchase_order or vendor_bill",
  "order_number": "string or null",
  "order_date": "YYYY-MM-DD (REQUIRED)",
  "delivery_date": "YYYY-MM-DD (REQUIRED)",
  "currency": "VND or USD or EUR or null (default VND if not stated)",
  "payment_method": "string or null",
  "recipient_name": "string or null",
  "description": "string or null",
  "customer_name": "string or null",
  "customer_tax_code": "string or null",
  "vendor_name": "string or null",
  "vendor_tax_code": "string or null",
  "delivery_address": "string or null",
  "total_amount": "number (REQUIRED)",
  "discount_amount": number_or_null,
  "tax_amount": number_or_null,
  "items": [
    {
      "product_code": "string or null",
      "product_name": "string",
      "quantity": "number (REQUIRED)",
      "unit": "string (REQUIRED)",
      "unit_price": number_or_null,
      "discount_rate": number_or_null,
      "discount_amount": number_or_null,
      "tax_rate": number_or_null,
      "line_total": "number (REQUIRED)"
    }
  ]
}
IMPORTANT: 
- order_date, delivery_date, total_amount are REQUIRED — extract them carefully
- For each item: quantity, unit, line_total are REQUIRED
- Items must never be empty if products are listed
- Skip rows with no quantity AND no price (e.g. free-goods placeholder rows)
- If a field is missing use null, but try your best to find REQUIRED fields
- MULTI-PAGE: The document may span multiple pages. Extract ALL items from ALL pages, not just the first page.
- If total_amount is NOT explicitly printed on the document, calculate it as the SUM of all items[].line_total (plus tax if applicable)
- NEVER use only items from the first page to calculate total — always include ALL pages

NUMBER FORMAT RULES (CRITICAL):
- Vietnamese documents use dots (.) as THOUSAND separators, NOT decimal points. Example: "1.076.328" means 1076328, NOT 1076.328
- All monetary amounts (total_amount, unit_price, line_total, discount_amount, tax_amount) must be returned as plain integers or numbers WITHOUT thousand separators. Example: "1.076.328" → 1076328, "25.000" → 25000
- For VND currency, amounts are always whole numbers (no decimals). Return them as integers.
- quantity can have decimals (e.g. 1.5 kg) — use dot as decimal separator only when the document clearly shows fractional quantities"""

# NVIDIA NIM giới hạn ảnh ~180k tokens → giữ ảnh nhỏ hơn 2.5MB sau encode
_MAX_IMAGE_BYTES = 2_500_000  # bytes trước khi base64


def _file_to_base64_images(file_path: str) -> list[tuple[str, str]]:
    """Returns list of (base64_string, media_type) for each page. PDF → one image per page."""
    path = Path(file_path)
    suffix = path.suffix.lower()

    if suffix == ".pdf":
        from pdf2image import convert_from_path
        images = convert_from_path(file_path, dpi=200)
        if not images:
            raise ValueError("Could not convert PDF to image")
    elif suffix in (".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tiff"):
        images = [Image.open(file_path)]
    else:
        raise ValueError(f"Unsupported file type: {suffix}")

    results = []
    for img in images:
        img = img.convert("RGB")

        # Resize nếu quá lớn
        max_side = 2048
        if max(img.size) > max_side:
            ratio = max_side / max(img.size)
            new_size = (int(img.width * ratio), int(img.height * ratio))
            img = img.resize(new_size, Image.LANCZOS)

        # Nén JPEG
        for quality in (90, 80, 70, 60):
            buf = io.BytesIO()
            img.save(buf, format="JPEG", quality=quality)
            raw_bytes = buf.getvalue()
            if len(raw_bytes) <= _MAX_IMAGE_BYTES:
                break

        results.append((base64.b64encode(raw_bytes).decode(), "image/jpeg"))

    return results


def _resolve_provider() -> str:
    """Trả về provider thực tế sẽ dùng: 'openrouter' hoặc 'nvidia'."""
    p = settings.OCR_PROVIDER.lower()
    if p == "openrouter":
        return "openrouter"
    if p == "nvidia":
        return "nvidia"
    # auto: dùng openrouter nếu có key, fallback nvidia
    return "openrouter" if settings.OPENROUTER_API_KEY else "nvidia"


def _get_ocr_credentials():
    """Get API key and model from DB first, fallback to env."""
    from app.database import SessionLocal
    from app.models.sys_config import SysConfig
    db = SessionLocal()
    try:
        key_row = db.query(SysConfig).filter(SysConfig.config_key == "openrouter_api_key").first()
        model_row = db.query(SysConfig).filter(SysConfig.config_key == "openrouter_model").first()
        api_key = (key_row.config_value if key_row and key_row.config_value else None) or settings.OPENROUTER_API_KEY
        model = (model_row.config_value if model_row and model_row.config_value else None) or settings.OPENROUTER_MODEL
        return api_key, model
    finally:
        db.close()


def _call_ocr(prompt: str, file_path: str) -> str:
    """Gọi OCR provider được chọn (OpenRouter hoặc NVIDIA NIM). Hỗ trợ multi-page."""
    page_images = _file_to_base64_images(file_path)
    provider = _resolve_provider()

    if provider == "openrouter":
        base_url = OPENROUTER_BASE_URL
        api_key, model = _get_ocr_credentials()
        extra_headers = {
            "HTTP-Referer": "https://ocr-risk.local",
            "X-Title": "OCR Risk",
        }
    else:
        base_url = NVIDIA_BASE_URL
        api_key = settings.NVIDIA_API_KEY
        model = settings.NVIDIA_MODEL
        extra_headers = {}

    if not api_key:
        raise ValueError("OCR API key chưa được cấu hình. Vào Settings để nhập API key.")

    # Build content with text prompt + all page images
    content = [{"type": "text", "text": prompt}]
    for b64, media_type in page_images:
        content.append({
            "type": "image_url",
            "image_url": {
                "url": f"data:{media_type};base64,{b64}",
                "detail": "high",
            },
        })

    payload = {
        "model": model,
        "messages": [
            {
                "role": "user",
                "content": content,
            }
        ],
        "max_tokens": 4096,
        "temperature": 0.1,
    }

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        **extra_headers,
    }

    with httpx.Client(timeout=180) as client:
        resp = client.post(
            f"{base_url}/chat/completions",
            headers=headers,
            json=payload,
        )
        resp.raise_for_status()

    return resp.json()["choices"][0]["message"]["content"]


def _extract_json(text: str) -> dict:
    text = text.strip()
    # Bóc JSON ra khỏi markdown code block nếu model trả về
    match = re.search(r"```(?:json)?\s*([\s\S]+?)\s*```", text)
    if match:
        text = match.group(1)
    # Thử parse trực tiếp
    return json.loads(text)


def extract_mst_and_type(file_path: str) -> dict:
    """Pass 1: chỉ lấy MST và loại chứng từ — nhanh, rẻ."""
    raw = _call_ocr(GENERIC_MST_PROMPT, file_path)
    try:
        result = _extract_json(raw)
        result["_raw"] = raw
        return result
    except Exception:
        return {"tax_code": None, "document_type": None, "_raw": raw}


def _normalize_vn_number(value) -> int | float | None:
    """Normalize Vietnamese number format: '1.076.328' → 1076328, '1076.328' → 1076328 (not 1076.328)."""
    if value is None:
        return None
    if isinstance(value, (int, float)):
        # If it looks like a wrongly-parsed VN number (e.g. 1076.328 should be 1076328)
        # Heuristic: if decimal part has 3 digits, it's likely a thousand separator
        if isinstance(value, float):
            s = str(value)
            if '.' in s:
                decimal_part = s.split('.')[1]
                if len(decimal_part) == 3:
                    return int(round(value * 1000))
        return value
    # String value
    s = str(value).strip().replace(' ', '').replace('\u00a0', '')
    if not s:
        return None
    # Remove currency symbols
    s = re.sub(r'[đĐ₫VND]', '', s, flags=re.IGNORECASE).strip()
    # Count dots and commas
    dot_count = s.count('.')
    comma_count = s.count(',')
    if dot_count > 1:
        # Multiple dots = thousand separators (VN format): 1.076.328
        s = s.replace('.', '')
    elif dot_count == 1 and comma_count == 0:
        # Single dot: check if decimal part is 3 digits (likely thousand sep)
        parts = s.split('.')
        if len(parts[1]) == 3 and len(parts[0]) >= 1:
            s = s.replace('.', '')
    if comma_count > 1:
        s = s.replace(',', '')
    elif comma_count == 1 and '.' not in s:
        parts = s.split(',')
        if len(parts[1]) == 3:
            s = s.replace(',', '')
        else:
            s = s.replace(',', '.')
    try:
        result = float(s)
        if result == int(result):
            return int(result)
        return result
    except (ValueError, TypeError):
        return None


def _normalize_extracted_amounts(data: dict) -> dict:
    """Post-process extracted data to fix Vietnamese number format issues."""
    amount_fields = ['total_amount', 'discount_amount', 'tax_amount']
    for field in amount_fields:
        if field in data and data[field] is not None:
            data[field] = _normalize_vn_number(data[field])
    
    items = data.get('items') or []
    for item in items:
        for field in ['unit_price', 'line_total', 'discount_amount']:
            if field in item and item[field] is not None:
                item[field] = _normalize_vn_number(item[field])
    return data


def extract_full_document(file_path: str, system_prompt: str | None = None) -> dict:
    """Pass 2: trích xuất toàn bộ dữ liệu với prompt của template (hoặc generic)."""
    prompt = system_prompt or GENERIC_FULL_PROMPT
    raw = _call_ocr(prompt, file_path)
    try:
        result = _extract_json(raw)
        return _normalize_extracted_amounts(result)
    except Exception:
        return {"items": [], "_raw": raw, "_parse_error": True}
