from sqlalchemy.orm import Session
from app.models.template import Template
from app.models.mapping import MSTMapping
from app.services.code_generator import generate_template_code
from app.services.ocr_service import extract_full_document, GENERIC_FULL_PROMPT

# ── Prompt riêng cho các format đặc biệt ─────────────────────────────────────

_OSIFOOD_PROMPT = """You are extracting data from an OSIFOOD purchase order sent to SATORI.
This document has an unusual layout: column NUMBERS (1)(2)(3)... appear at the TOP of the table,
and column NAMES appear at the BOTTOM. Map them as follows:
(1)=STT, (2)=BARCODE, (3)=MÃ GỢI NHỚ, (4)=TÊN HÀNG, (5)=QUI CÁCH THÙNG,
(6)=GIÁ VỐN ĐVỊ(0VAT), (7)=GIÁ VỐN KM, (8)=CƠ CẤU KM,
(9)=LƯỢNG LẺ (total individual items), (10)=LƯỢNG THÙNG (boxes), (11)=THÀNH TIỀN.

Use LƯỢNG LẺ as quantity, GIÁ VỐN ĐVỊ as unit_price, THÀNH TIỀN as line_total.
Header fields: look for STORE/TÊN CH=customer, ĐỊA CHỈ GIAO HÀNG=delivery_address,
Ngày đặt hàng=order_date, DH-SATORI or NCC code=order_number.

Return valid JSON only (no markdown):
{
  "document_type": "purchase_order",
  "order_number": "string or null",
  "order_date": "YYYY-MM-DD or null",
  "currency": "VND",
  "payment_method": null,
  "recipient_name": null,
  "description": null,
  "customer_name": "string or null",
  "customer_tax_code": null,
  "vendor_name": "SATORI",
  "vendor_tax_code": "0302056457",
  "delivery_address": "string or null",
  "total_amount": number_or_null,
  "discount_amount": null,
  "tax_amount": null,
  "items": [{"product_code": "string or null", "product_name": "string", "quantity": number_or_null,
    "unit": "string or null", "unit_price": number_or_null, "discount_rate": null,
    "discount_amount": null, "tax_rate": null, "line_total": number_or_null}]
}"""

_SEVEN_ELEVEN_PROMPT = """You are extracting data from a 7-ELEVEN Vietnam PHIẾU GIAO HÀNG (Delivery Note).
This is a delivery confirmation document, NOT a standard purchase order — it has no unit prices.

Field mapping:
- order_number = "Số phiếu giao hàng" or "Supplier Delivery ID"
- order_date = "Ngày xác nhận" (Confirmation Date) in YYYY-MM-DD
- vendor_name = "Tên (Company Name)" under THÔNG TIN BÊN GIAO HÀNG section = SATORI
- customer_name = "Kho (CDC)" under THÔNG TIN BÊN NHẬN HÀNG = 7-ELEVEN
- delivery_address = warehouse address from THÔNG TIN KHO GIAO HÀNG
- recipient_name = "Người liên hệ (Attn)"
- items: read from the table — use "Số Lượng Giao Hàng Theo Đơn Vị Cơ Sở" as quantity,
  "Đơn Vị Cơ Sở (Base Unit)" as unit, "Mã SP của NCC (Supplier Product ID)" or
  "Mã Vạch (Store order UOM Barcode)" as product_code, "Tên Hàng Hóa (Product Name)" as product_name.
  unit_price = null (not on this document).

Return valid JSON only (no markdown):
{
  "document_type": "purchase_order",
  "order_number": "string or null",
  "order_date": "YYYY-MM-DD or null",
  "currency": "VND",
  "payment_method": null,
  "recipient_name": "string or null",
  "description": null,
  "customer_name": "string or null",
  "customer_tax_code": null,
  "vendor_name": "SATORI",
  "vendor_tax_code": "0302056457",
  "delivery_address": "string or null",
  "total_amount": null,
  "discount_amount": null,
  "tax_amount": null,
  "items": [{"product_code": "string or null", "product_name": "string", "quantity": number_or_null,
    "unit": "string or null", "unit_price": null, "discount_rate": null,
    "discount_amount": null, "tax_rate": null, "line_total": null}]
}"""

_COOPFOOD_PROMPT = """You are extracting data from a Co.opfood / Co.opmart purchase order
generated by JDA Software (system POM343). The format uses English abbreviations.

Field mapping:
- order_number = "P/O Number"
- order_date = "Date" (top right, format DD/MM/YY → convert to YYYY-MM-DD)
- delivery_address = "Ship To" section
- customer_name = "Bill To" company name
- vendor_name = company after "Vendor:" field = SATORI
- currency = "Currency" field (VND)
- payment_method = "Terms" field (e.g. "10TH PROX/CUTOFF 5TH")
- items table columns: "SKU Number"=product_code, "Description"=product_name,
  "Vendor Part No."=product_code (use if SKU is internal), "Buy U/M"=unit,
  "Net Buy Cost"=unit_price (cost per case/box), "Ord/CS"=quantity (number of cases ordered),
  "Extended Cost"=line_total.
- total_amount = "Total" at the bottom
- tax_amount = null (tax shown separately as VAT 8% etc.)

Return valid JSON only (no markdown):
{
  "document_type": "purchase_order",
  "order_number": "string or null",
  "order_date": "YYYY-MM-DD or null",
  "currency": "VND",
  "payment_method": "string or null",
  "recipient_name": null,
  "description": null,
  "customer_name": "string or null",
  "customer_tax_code": null,
  "vendor_name": "SATORI",
  "vendor_tax_code": "0302056457",
  "delivery_address": "string or null",
  "total_amount": number_or_null,
  "discount_amount": null,
  "tax_amount": null,
  "items": [{"product_code": "string or null", "product_name": "string", "quantity": number_or_null,
    "unit": "string or null", "unit_price": number_or_null, "discount_rate": null,
    "discount_amount": null, "tax_rate": null, "line_total": number_or_null}]
}"""

_BUILTIN_TEMPLATES = [
    {
        "code": "TPL_OSIFOOD",
        "name": "OsiFood — Cột đánh số (1)-(10)",
        "document_type": "purchase_order",
        "system_prompt": _OSIFOOD_PROMPT,
        "field_aliases": {"order_number": ["DH-SATORI", "ĐƠN ĐẶT HÀNG NCC"]},
        "output_schema": {},
    },
    {
        "code": "TPL_7ELEVEN",
        "name": "7-Eleven — Phiếu giao hàng (Delivery Note)",
        "document_type": "purchase_order",
        "system_prompt": _SEVEN_ELEVEN_PROMPT,
        "field_aliases": {"order_number": ["Supplier Delivery ID", "Số phiếu giao hàng"]},
        "output_schema": {},
    },
    {
        "code": "TPL_COOPFOOD",
        "name": "Co.opfood / Co.opmart — JDA Format",
        "document_type": "purchase_order",
        "system_prompt": _COOPFOOD_PROMPT,
        "field_aliases": {
            "order_number": ["P/O Number"],
            "items.unit_price": ["Net Buy Cost", "Buy Cost"],
            "items.quantity": ["Ord/CS", "Ord/Pcs"],
            "items.line_total": ["Extended Cost"],
        },
        "output_schema": {},
    },
]

# Tên hiển thị tiếng Việt cho từng field chuẩn
_FIELD_LABELS_VI = {
    "order_number": "Số chứng từ / số đơn hàng",
    "order_date": "Ngày chứng từ",
    "invoice_number": "Số hóa đơn",
    "invoice_date": "Ngày hóa đơn",
    "currency": "Tiền tệ",
    "payment_method": "Hình thức thanh toán",
    "recipient_name": "Người nhận hàng",
    "description": "Nội dung / ghi chú",
    "customer_name": "Tên khách hàng",
    "customer_tax_code": "MST khách hàng",
    "vendor_name": "Tên nhà cung cấp",
    "vendor_tax_code": "MST nhà cung cấp",
    "delivery_address": "Địa chỉ giao hàng",
    "total_amount": "Tổng tiền hàng",
    "discount_amount": "Tiền chiết khấu",
    "tax_amount": "Tiền thuế",
    "items.product_code": "Mã hàng hóa",
    "items.product_name": "Tên hàng hóa",
    "items.quantity": "Số lượng",
    "items.unit": "Đơn vị tính",
    "items.unit_price": "Đơn giá",
    "items.discount_rate": "Tỷ lệ chiết khấu (%)",
    "items.discount_amount": "Tiền chiết khấu dòng",
    "items.tax_rate": "Thuế suất VAT (%)",
    "items.line_total": "Thành tiền",
}


_FORMAT_HINT_TO_TEMPLATE = {
    "osifood": "TPL_OSIFOOD",
    "seven_eleven": "TPL_7ELEVEN",
    "coopfood": "TPL_COOPFOOD",
}


def find_template(
    db: Session,
    tax_code: str | None,
    document_type: str | None,
    format_hint: str | None = None,
    order_number: str | None = None,
) -> Template | None:
    # Ưu tiên 1: template gắn partner qua MST
    if tax_code and document_type:
        mst = db.query(MSTMapping).filter(MSTMapping.tax_code == tax_code).first()
        if mst:
            template = (
                db.query(Template)
                .filter(
                    Template.partner_id == mst.partner_id,
                    Template.document_type == document_type,
                    Template.is_active,
                )
                .first()
            )
            if template:
                return template

    # Ưu tiên 2: template theo tiền tố mã PO (_po_prefix)
    if order_number and document_type:
        candidates = (
            db.query(Template)
            .filter(
                Template.document_type == document_type,
                Template.is_active == True,
                Template.field_aliases.isnot(None),
            )
            .all()
        )
        for t in candidates:
            prefixes = (t.field_aliases or {}).get("_po_prefix", [])
            if any(order_number.startswith(p) for p in prefixes if p):
                return t

    # Ưu tiên 3: built-in template theo format_hint từ pass 1
    if format_hint and format_hint != "standard":
        code = _FORMAT_HINT_TO_TEMPLATE.get(format_hint)
        if code:
            t = db.query(Template).filter(Template.code == code, Template.is_active == True).first()
            if t:
                return t

    return None


def get_generic_template_prompt() -> str:
    return GENERIC_FULL_PROMPT


def create_template(
    db: Session,
    partner_id,
    document_type: str,
    name: str,
    system_prompt: str,
    output_schema: dict,
    field_aliases: dict | None = None,
) -> Template:
    code = generate_template_code(db)
    template = Template(
        code=code,
        partner_id=partner_id,
        document_type=document_type,
        name=name,
        system_prompt=system_prompt,
        output_schema=output_schema,
        field_aliases=field_aliases or {},
    )
    db.add(template)
    db.commit()
    db.refresh(template)
    return template


def suggest_template_from_file(file_path: str) -> dict:
    """Extract document with generic prompt and return suggested fields for template creation."""
    extracted = extract_full_document(file_path)
    suggested_fields = {
        "document_type": extracted.get("document_type", ""),
        "order_number": "string",
        "order_date": "YYYY-MM-DD",
        "currency": "string",
        "payment_method": "string",
        "recipient_name": "string",
        "description": "string",
        "customer_name": "string",
        "customer_tax_code": "string",
        "vendor_name": "string",
        "vendor_tax_code": "string",
        "delivery_address": "string",
        "total_amount": "number",
        "discount_amount": "number",
        "tax_amount": "number",
        "items": {
            "product_code": "string",
            "product_name": "string",
            "quantity": "number",
            "unit": "string",
            "unit_price": "number",
            "discount_rate": "number",
            "discount_amount": "number",
            "tax_rate": "number",
            "line_total": "number",
        },
    }
    default_aliases = {field: [] for field in _FIELD_LABELS_VI}
    return {
        "suggested_fields": suggested_fields,
        "raw_extracted": extracted,
        "suggested_aliases": default_aliases,
    }


def build_system_prompt_from_schema(output_schema: dict) -> str:
    import json
    schema_str = json.dumps(output_schema, ensure_ascii=False, indent=2)
    return (
        "You are an expert at extracting structured data from Vietnamese business documents "
        "(purchase orders and VAT invoices). "
        "Extract all fields and return valid JSON only (no markdown).\n"
        f"Required output schema:\n{schema_str}\n"
        "For missing fields use null. Items must be an array."
    )


def seed_builtin_templates(db: Session) -> None:
    """Tạo sẵn các template cho format đặc biệt nếu chưa tồn tại."""
    for tpl in _BUILTIN_TEMPLATES:
        exists = db.query(Template).filter(Template.code == tpl["code"]).first()
        if not exists:
            db.add(Template(
                code=tpl["code"],
                partner_id=None,
                document_type=tpl["document_type"],
                name=tpl["name"],
                system_prompt=tpl["system_prompt"],
                output_schema=tpl["output_schema"],
                field_aliases=tpl.get("field_aliases", {}),
                is_active=True,
            ))
    db.commit()


def build_prompt_with_aliases(field_aliases: dict) -> str:
    """Sinh OCR prompt từ GENERIC_FULL_PROMPT + alias mapping của user.

    field_aliases = {"payment_method": ["HTTT", "P.thức TT"], "recipient_name": ["NNH"]}
    Keys bắt đầu bằng '_' (như _po_prefix) là metadata nội bộ, không đưa vào prompt.
    """
    if not field_aliases:
        return GENERIC_FULL_PROMPT

    alias_lines = []
    for field, aliases in field_aliases.items():
        if field.startswith("_") or not aliases:
            continue
        label_vi = _FIELD_LABELS_VI.get(field, field)
        alias_quoted = ", ".join(f'"{a}"' for a in aliases)
        alias_lines.append(f'- {label_vi} ("{field}"): label trên chứng từ có thể là {alias_quoted}')

    if not alias_lines:
        return GENERIC_FULL_PROMPT

    alias_block = "\n".join(alias_lines)
    return (
        f"{GENERIC_FULL_PROMPT}\n\n"
        "QUAN TRỌNG — Alias mapping riêng cho chứng từ này:\n"
        f"{alias_block}\n\n"
        "Khi tìm giá trị, hãy nhận diện cả các label thay thế được liệt kê ở trên."
    )
